pipeline {
    agent any
    stages {
        stage('deploy') {
            steps {
                bat "docker rm -f webserver"
                bat "docker rm -f frontend"
                bat "docker run --name webserver --link frontend:frontend -d -p 8083:80 webserver:${GIT_BRANCH}-${BUILD_NUMBER} "
                bat "docker run --name frontend -d -p 3000:3000 frontend:${GIT_BRANCH}-${BUILD_NUMBER}"
            }
        }
    }
    post {
        success {
            echo "Deploy success"
            echo "${BUILD_NUMBER}"
            
        }
    }
}